[build]
  command = "npx next build"
  publish = ".next"

[functions]
  # Use esbuild for better tree-shaking and smaller bundles
  node_bundler = "esbuild"
  
  # Exclude unnecessary files from function bundle
  included_files = [
    ".next/**",
    "!.next/cache/**",
    "!.next/standalone/**",
    "!.next/static/**",
    ".env",
    ".env.production",
    ".env.local",
    ".env.production.local"
  ]
  
  # External packages to reduce bundle size
  external_node_modules = [
    "@sentry/nextjs",
    "sharp",
    "canvas",
    "bufferutil",
    "utf-8-validate"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optimize build performance
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
