/**
 * ATProto OAuth library plumbing.
 *
 * These tables back the StateStore and SessionStore interfaces required
 * by @atproto/oauth-client-node. They are NOT domain concepts — they are
 * library implementation that happens to need persistence (in-memory state
 * breaks on Vercel/serverless where requests can hit different function
 * instances).
 *
 * Kept separate from schema.ts so domain tables and infra don't share
 * visual surface. If we later move state to signed cookies or Redis,
 * deleting this file is the only schema change required.
 *
 * Crucially, sessions are keyed by DID, not user_id. The library doesn't
 * know about EPTSS users — it manages OAuth sessions keyed by the
 * authenticated subject (DID). The user_id ↔ DID crosswalk lives in
 * `user_atproto_identities` (a domain table in schema.ts).
 */
import { pgTable, text, timestamp, jsonb, index } from "drizzle-orm/pg-core";

/**
 * Transient OAuth state.
 *
 * Written by StateStore.set() when /api/atproto/link initiates an OAuth
 * flow; fetched once by /api/atproto/callback on completion, then deleted.
 * Rows past expires_at are stale and can be swept periodically (or
 * opportunistically on each write).
 *
 * Key is the opaque OAuth state identifier generated by the library.
 * Value is the serialized state blob (also library-controlled shape).
 */
export const atprotoOauthState = pgTable("atproto_oauth_state", {
  key: text("key").primaryKey(),
  value: jsonb("value").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  expiresAt: timestamp("expires_at").notNull(),
}, (table) => ({
  expiresAtIdx: index("atproto_oauth_state_expires_at_idx").on(table.expiresAt),
}));

export type AtprotoOauthState = typeof atprotoOauthState.$inferSelect;
export type NewAtprotoOauthState = typeof atprotoOauthState.$inferInsert;

/**
 * Long-lived OAuth sessions, keyed by DID (the OAuth "sub").
 *
 * Written by SessionStore.set() after a successful OAuth dance, and on
 * every token refresh (the library rotates refresh tokens per spec). Read
 * by SessionStore.get() whenever the app wants to make a request on the
 * user's behalf.
 *
 * Value is the serialized Session blob (library-controlled shape: access
 * token, refresh token, DPoP key, token expiry, etc.). Treat as a
 * credential — never expose via API responses, never log.
 *
 * The (user_id, did) link lives in user_atproto_identities (domain).
 * Joining gives "who has this session" but the library doesn't need that
 * join — it just stores blobs by DID.
 *
 * On unlink, EPTSS code should both soft-delete the user_atproto_identities
 * row AND delete the row here (and ideally call client.revoke(did)).
 */
export const atprotoOauthSessions = pgTable("atproto_oauth_sessions", {
  did: text("did").primaryKey(),
  value: jsonb("value").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type AtprotoOauthSession = typeof atprotoOauthSessions.$inferSelect;
export type NewAtprotoOauthSession = typeof atprotoOauthSessions.$inferInsert;
