/**
 * POST /api/atproto/link
 *
 * Initiates the OAuth dance to link the current EPTSS user to a Bluesky DID.
 *
 * Caller posts JSON: { handle: "nate.bsky.social" }
 * Response: { url: "https://bsky.social/oauth/authorize?..." }
 *
 * The client redirects the browser to that URL. The user authorizes on
 * their PDS; the PDS redirects them to /api/atproto/callback with a code,
 * which exchanges for a session and saves the identity.
 *
 * The EPTSS user_id is stashed in OAuth state so the callback knows whose
 * identity to write. The state is generated by us as a JSON-encoded blob
 * — the library passes it through verbatim (separate from its own internal
 * CSRF state, which it manages itself).
 *
 * Auth-guarded: caller must be a signed-in EPTSS user (via Supabase).
 */
import { NextRequest, NextResponse } from "next/server";
import { getAuthUser } from "@eptss/auth/server";
import { getOAuthClient } from "@/lib/atproto/client";

export const dynamic = "force-dynamic";

export async function POST(request: NextRequest) {
  const { userId } = await getAuthUser();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { handle?: unknown };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const handleRaw = body.handle;
  if (typeof handleRaw !== "string" || handleRaw.trim().length === 0) {
    return NextResponse.json({ error: "handle (string) required" }, { status: 400 });
  }
  const handle = handleRaw.trim();

  try {
    const client = getOAuthClient();
    const url = await client.authorize(handle, {
      // Custom app-state — comes back verbatim in callback's result.state.
      // We use it to carry userId through the redirect dance, since the
      // library doesn't know about EPTSS users.
      state: JSON.stringify({ userId }),
    });
    return NextResponse.json({ url: url.toString() });
  } catch (err) {
    // Handle resolution failures, PDS unreachable, etc. The user's input
    // (handle) was probably wrong, OR bsky's authz server is down.
    const message = err instanceof Error ? err.message : "unknown error";
    console.error("OAuth authorize() failed:", err);
    return NextResponse.json(
      { error: "Could not start link flow", detail: message },
      { status: 502 },
    );
  }
}
