name: Auth Monitoring

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GMAIL_USER_EMAIL: ${{ secrets.GMAIL_USER_EMAIL }}  # Only needed if running in staging
      ENVIRONMENT: 'production'  # This will skip the magic link test

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run auth test
        run: npm run cypress:run -- --spec "cypress/e2e/monitoring/auth.cy.ts"
        env:
          CYPRESS_ENVIRONMENT: 'production'  # This ensures magic link test is skipped
