name: Auth Monitoring

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GMAIL_USER_EMAIL: ${{ secrets.GMAIL_USER_EMAIL }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      ENVIRONMENT: 'production'
      CYPRESS_ENVIRONMENT: 'production'
      DEBUG: cypress:server:request,cypress:server:response,cypress:*:error  # Only show request/response and errors

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run auth test
        run: |
          mkdir -p cypress/logs
          # Show all console output and test results
          npm run cypress:production 2>&1 | tee cypress/logs/test-run.log
        env:
          CYPRESS_GMAIL_USER_EMAIL: ${{ secrets.GMAIL_USER_EMAIL }}
          CYPRESS_GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          CYPRESS_GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          CYPRESS_GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          CYPRESS_DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-logs
          path: |
            cypress/logs/
            cypress/screenshots/
            cypress/videos/
