name: Daily Song Post

on:
  schedule:
    # Runs at 11:00 AM PST (19:00 UTC) every day
    - cron: '0 19 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  post-song:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Debug environment variables
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "Username exists: ${{ secrets.BLUESKY_USERNAME != '' }}"
          echo "Password exists: ${{ secrets.BLUESKY_PASSWORD != '' }}"

      - name: Run song posting script
        run: bun run post-song

        env:
          ENVIRONMENT: Pioneer
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }} 