name: Test Reporter

on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
        description: 'Name of the test being run'
      environment:
        required: true
        type: string
        description: 'Environment the test is running in'
      start-time:
        required: true
        type: string
        description: 'Test start time in nanoseconds'
      exit-code:
        required: true
        type: string
        description: 'Exit code from the test run'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Report test results
        run: |
          # Map exit code to status
          if [ "${{ inputs.exit-code }}" = "0" ]; then
            STATUS="success"
          else
            STATUS="failure"
          fi
          
          # Calculate duration in milliseconds
          end_time=$(date +%s%N)
          duration=$(( ($end_time - ${{ inputs.start-time }}) / 1000000 ))
          
          # Get current timestamp in ISO format
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Create the request payload
          REQUEST_DATA="{\"testName\":\"${{ inputs.test-name }}\",\"status\":\"$STATUS\",\"errorMessage\":null,\"duration\":$duration,\"startedAt\":\"$TIMESTAMP\",\"environment\":\"${{ inputs.environment }}\"}"
          
          echo "Sending test results..."
          echo "Request payload:"
          echo "$REQUEST_DATA" | jq .
          
          # Execute the curl command
          curl -v -X POST \
            -H "Content-Type: application/json" \
            -d "$REQUEST_DATA" \
            https://everyoneplaysthesamesong.com/api/test-report
